// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

namespace My_Bittrex_2.Model
{

    internal class AccountCurrencies
    {
        public string Currency { get; set; }
        public double Balance { get; set; }
        public double Available { get; set; }
        public double Pending { get; set; }
        public string CryptoAddress { get; set; }
        public bool Requested { get; set; }
        public object Uuid { get; set; }
    }

    internal class AccountWrapper
    {
        public bool Success { get; set; }
        public string Message { get; set; }
        public AccountCurrencies[] AccountCurrencies { get; set; }
    }

}
